# Default values for Fn
imagePullPolicy: IfNotPresent

fn:
  service:
    port: 80
    type: LoadBalancer
    annotations: {}

fnlb:
  image: fnproject/fnlb:latest

fnserver:
  image: fnproject/fnserver:latest
  logLevel: info
  resources: {}
  nodeSelector: {}
  tolerations: []


ui:
  enabled: true
  fnui:
    image: fnproject/ui:latest
    resources: {}
  flowui:
    image: fnproject/flow:ui
    resources: {}
  service:
    flowuiPort: 3000
    fnuiPort: 80
    type: LoadBalancer
    annotations: {}


flow:
  image: fnproject/flow:latest
  logLevel: info
  service:
    port: 80
    type: ClusterIP
    annotations: {}
  resources: {}


##
## MySQL chart configuration
##
mysql:
  persistence:
    enabled: false
    nodeSelector: mysql-storage
    ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
    ## Default: volume.alpha.kubernetes.io/storage-class: default
    ##
    # storageClass:
    storageClass: mysql
    accessMode: ReadWriteOnce
    size: 8Gi

  mysqlDatabase: fndb
  mysqlUser: fnapp
  mysqlPassword: boomsauce

##
## Redis chart configuration
##
redis:
  persistence:
    enabled: false
    nodeSelector: redis-storage
    storageClass: redis
    accessMode: ReadWriteOnce
    size: 8Gi
  usePassword: false

## Ingress configuration.
## ref: https://kubernetes.io/docs/user-guide/ingress/
##
ingress:
  enabled: false
